#!/bin/bash
# m4a2ogg converts all m4a to ogg in a directory.
# Arenlor
#for i in *.m4a
#do
#./ffmpeg -y -i "$i" "$i".wav
#./oggenc -q10 "$i".wav
#done
#rename 's/m4a.ogg/ogg/g' *
#rm *.wav
#rm *.m4a
#exit 0

#for f in *.flac , *.m4a , *.ogg ; do ffmpeg -i "$f" -ab 320k "${f%.m4a}.mp3"; done

MOVIES=~/Documents/projects/web/imonchristmashw/sounds
find "$MOVIES" -name '*.m4a' -exec sh -c '~/Documents/projects/web/imonchristmashw/sounds/ffmpeg -i "$0" -c:a libvorbis -q:a 5 "${0%%.mp4}.ogg"' {} \;
exit;